# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9790d7245c6b9c9f2dc2da6000df1d06873da6b2a70fde2697fde9e48d82c2e08463fc8898a670fa351821321dab9d5de183fa76011abc9f313d0cc03b088ac

test:
  secret_key_base: c0fb555ba262cf2b4dc003f6de8e0408b0a7f7f768448ac7ac5083ba0f0704e82e23489568abfc0748c48090c363e6ede0af709b35cab85e5a4c7f2cbe029ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
